# 接続情報
connection = {
  address = "127.0.0.1",
  port    = 5198,
}

# チューナー情報
# - name はすべてのチューナーで一意となるようにする
# - path はそれぞれのデバイスでチューナーを識別できる文字列を設定する
# - チューナー設定が存在しない場合は各デバイスで標準の名前を付ける
# - チューナーが存在しないチューナー設定は無視する
tuners = [
  { name = "PT3_S0", path = "PT3/Bus:0/Device:0/ISDB-S/0", },
  { name = "PT3_S1", path = "PT3/Bus:0/Device:0/ISDB-S/1", },
  { name = "PT3_S2", path = "PT3/Bus:0/Device:1/ISDB-S/0", },
  { name = "PT3_S3", path = "PT3/Bus:0/Device:1/ISDB-S/1", },
  { name = "PT3_T0", path = "PT3/Bus:0/Device:0/ISDB-T/0", },
  { name = "PT3_T1", path = "PT3/Bus:0/Device:0/ISDB-T/1", },
  { name = "PT3_T2", path = "PT3/Bus:0/Device:1/ISDB-T/0", },
  { name = "PT3_T3", path = "PT3/Bus:0/Device:1/ISDB-T/1", },
]

# チャンネル情報
spaces = [
  "BS",    # [0]
  "CS110", # [1]
  "UHF",   # [2]
  "CATV",  # [3]
  "VHF",   # [4]
]
channels = [
  { name = "BS01/TS0 BS朝日",                 space = 0, index =  0, channel =   0, tsid = 16400, },
  { name = "BS01/TS1 BS-TBS",                 space = 0, index =  1, channel =   0, tsid = 16401, },
  { name = "BS01/TS2 BSテレ東",               space = 0, index =  2, channel =   0, tsid = 16402, },
  { name = "BS03/TS0 WOWOWプライム",          space = 0, index =  3, channel =   1, tsid = 16432, },
  { name = "BS03/TS1 BSアニマックス",         space = 0, index =  4, channel =   1, tsid = 17969, },
  { name = "BS03/TS2 BS釣りビジョン",         space = 0, index =  5, channel =   1, tsid = 17970, },
  { name = "BS05/TS0 WOWOWライブ",            space = 0, index =  6, channel =   2, tsid = 17488, },
  { name = "BS05/TS1 WOWOWシネマ",            space = 0, index =  7, channel =   2, tsid = 17489, },
  { name = "BS09/TS0 BS11イレブン",           space = 0, index =  8, channel =   4, tsid = 16528, },
  { name = "BS09/TS2 BS12トゥエルビ",         space = 0, index =  9, channel =   4, tsid = 16530, },
  { name = "BS13/TS0 BS日テレ",               space = 0, index = 10, channel =   6, tsid = 16592, },
  { name = "BS13/TS1 BSフジ",                 space = 0, index = 11, channel =   6, tsid = 16593, },
  { name = "BS13/TS2 放送大学",               space = 0, index = 12, channel =   6, tsid = 18130, },
  { name = "BS15/TS1 NHKBS1",                 space = 0, index = 13, channel =   7, tsid = 16625, },
  { name = "BS15/TS2 BS10スターチャンネル",   space = 0, index = 14, channel =   7, tsid = 16626, },
  { name = "BS15/TS3 BS10",                   space = 0, index = 15, channel =   7, tsid = 18675, },
  { name = "BS19/TS0 J SPORTS 4",             space = 0, index = 16, channel =   9, tsid = 18224, },
  { name = "BS19/TS1 J SPORTS 1",             space = 0, index = 17, channel =   9, tsid = 18225, },
  { name = "BS19/TS2 J SPORTS 2",             space = 0, index = 18, channel =   9, tsid = 18226, },
  { name = "BS19/TS3 J SPORTS 3",             space = 0, index = 19, channel =   9, tsid = 18227, },
  { name = "BS21/TS0 WOWOWプラス",            space = 0, index = 20, channel =  10, tsid = 18256, },
  { name = "BS21/TS1 日本映画専門チャンネル", space = 0, index = 21, channel =  10, tsid = 18257, },
  { name = "BS21/TS2 グリーンチャンネル",     space = 0, index = 22, channel =  10, tsid = 18258, },
  { name = "BS23/TS0 ディズニーチャンネル",   space = 0, index = 23, channel =  11, tsid = 18288, },
  { name = "BS23/TS1 BSよしもと",             space = 0, index = 24, channel =  11, tsid = 18801, },
  { name = "BS23/TS3 BS松竹東急",             space = 0, index = 25, channel =  11, tsid = 18803, },
  { name = "ND02",                            space = 1, index =  0, channel =  12, tsid = 24608, },
  { name = "ND04",                            space = 1, index =  1, channel =  13, tsid = 28736, },
  { name = "ND06",                            space = 1, index =  2, channel =  14, tsid = 28768, },
  { name = "ND08",                            space = 1, index =  3, channel =  15, tsid = 24704, },
  { name = "ND10",                            space = 1, index =  4, channel =  16, tsid = 24736, },
  { name = "ND12",                            space = 1, index =  5, channel =  17, tsid = 28864, },
  { name = "ND14",                            space = 1, index =  6, channel =  18, tsid = 28896, },
  { name = "ND16",                            space = 1, index =  7, channel =  19, tsid = 28928, },
  { name = "ND18",                            space = 1, index =  8, channel =  20, tsid = 28960, },
  { name = "ND20",                            space = 1, index =  9, channel =  21, tsid = 28992, },
  { name = "ND22",                            space = 1, index = 10, channel =  22, tsid = 29024, },
  { name = "ND24",                            space = 1, index = 11, channel =  23, tsid = 29056, },
  { name = "13ch",                            space = 2, index =  0, channel =  63, tsid =     0, },
  { name = "14Ch",                            space = 2, index =  1, channel =  64, tsid =     0, },
  { name = "15Ch",                            space = 2, index =  2, channel =  65, tsid =     0, },
  { name = "16Ch",                            space = 2, index =  3, channel =  66, tsid =     0, },
  { name = "17Ch",                            space = 2, index =  4, channel =  67, tsid =     0, },
  { name = "18Ch",                            space = 2, index =  5, channel =  68, tsid =     0, },
  { name = "19Ch",                            space = 2, index =  6, channel =  69, tsid =     0, },
  { name = "20Ch",                            space = 2, index =  7, channel =  70, tsid =     0, },
  { name = "21Ch",                            space = 2, index =  8, channel =  71, tsid =     0, },
  { name = "22Ch",                            space = 2, index =  9, channel =  72, tsid =     0, },
  { name = "23Ch",                            space = 2, index = 10, channel =  73, tsid =     0, },
  { name = "24Ch",                            space = 2, index = 11, channel =  74, tsid =     0, },
  { name = "25Ch",                            space = 2, index = 12, channel =  75, tsid =     0, },
  { name = "26Ch",                            space = 2, index = 13, channel =  76, tsid =     0, },
  { name = "27Ch",                            space = 2, index = 14, channel =  77, tsid =     0, },
  { name = "28Ch",                            space = 2, index = 15, channel =  78, tsid =     0, },
  { name = "29Ch",                            space = 2, index = 16, channel =  79, tsid =     0, },
  { name = "30Ch",                            space = 2, index = 17, channel =  80, tsid =     0, },
  { name = "31Ch",                            space = 2, index = 18, channel =  81, tsid =     0, },
  { name = "32Ch",                            space = 2, index = 19, channel =  82, tsid =     0, },
  { name = "33Ch",                            space = 2, index = 20, channel =  83, tsid =     0, },
  { name = "34Ch",                            space = 2, index = 21, channel =  84, tsid =     0, },
  { name = "35Ch",                            space = 2, index = 22, channel =  85, tsid =     0, },
  { name = "36Ch",                            space = 2, index = 23, channel =  86, tsid =     0, },
  { name = "37Ch",                            space = 2, index = 24, channel =  87, tsid =     0, },
  { name = "38Ch",                            space = 2, index = 25, channel =  88, tsid =     0, },
  { name = "39Ch",                            space = 2, index = 26, channel =  89, tsid =     0, },
  { name = "40Ch",                            space = 2, index = 27, channel =  90, tsid =     0, },
  { name = "41Ch",                            space = 2, index = 28, channel =  91, tsid =     0, },
  { name = "42Ch",                            space = 2, index = 29, channel =  92, tsid =     0, },
  { name = "43Ch",                            space = 2, index = 30, channel =  93, tsid =     0, },
  { name = "44Ch",                            space = 2, index = 31, channel =  94, tsid =     0, },
  { name = "45Ch",                            space = 2, index = 32, channel =  95, tsid =     0, },
  { name = "46Ch",                            space = 2, index = 33, channel =  96, tsid =     0, },
  { name = "47Ch",                            space = 2, index = 34, channel =  97, tsid =     0, },
  { name = "48Ch",                            space = 2, index = 35, channel =  98, tsid =     0, },
  { name = "49Ch",                            space = 2, index = 36, channel =  99, tsid =     0, },
  { name = "50Ch",                            space = 2, index = 37, channel = 100, tsid =     0, },
  { name = "51Ch",                            space = 2, index = 38, channel = 101, tsid =     0, },
  { name = "52Ch",                            space = 2, index = 39, channel = 102, tsid =     0, },
  { name = "53Ch",                            space = 2, index = 40, channel = 103, tsid =     0, },
  { name = "54Ch",                            space = 2, index = 41, channel = 104, tsid =     0, },
  { name = "55Ch",                            space = 2, index = 42, channel = 105, tsid =     0, },
  { name = "56Ch",                            space = 2, index = 43, channel = 106, tsid =     0, },
  { name = "57Ch",                            space = 2, index = 44, channel = 107, tsid =     0, },
  { name = "58Ch",                            space = 2, index = 45, channel = 108, tsid =     0, },
  { name = "59Ch",                            space = 2, index = 46, channel = 109, tsid =     0, },
  { name = "60Ch",                            space = 2, index = 47, channel = 110, tsid =     0, },
  { name = "61Ch",                            space = 2, index = 48, channel = 111, tsid =     0, },
  { name = "62Ch",                            space = 2, index = 49, channel = 112, tsid =     0, },
  { name = "C13Ch",                           space = 3, index =  0, channel =   3, tsid =     0, },
  { name = "C14Ch",                           space = 3, index =  1, channel =   4, tsid =     0, },
  { name = "C15Ch",                           space = 3, index =  2, channel =   5, tsid =     0, },
  { name = "C16Ch",                           space = 3, index =  3, channel =   6, tsid =     0, },
  { name = "C17Ch",                           space = 3, index =  4, channel =   7, tsid =     0, },
  { name = "C18Ch",                           space = 3, index =  5, channel =   8, tsid =     0, },
  { name = "C19Ch",                           space = 3, index =  6, channel =   9, tsid =     0, },
  { name = "C20Ch",                           space = 3, index =  7, channel =  10, tsid =     0, },
  { name = "C21Ch",                           space = 3, index =  8, channel =  11, tsid =     0, },
  { name = "C22Ch",                           space = 3, index =  9, channel =  12, tsid =     0, },
  { name = "C23Ch",                           space = 3, index = 10, channel =  22, tsid =     0, },
  { name = "C24Ch",                           space = 3, index = 11, channel =  23, tsid =     0, },
  { name = "C25Ch",                           space = 3, index = 12, channel =  24, tsid =     0, },
  { name = "C26Ch",                           space = 3, index = 13, channel =  25, tsid =     0, },
  { name = "C27Ch",                           space = 3, index = 14, channel =  26, tsid =     0, },
  { name = "C28Ch",                           space = 3, index = 15, channel =  27, tsid =     0, },
  { name = "C29Ch",                           space = 3, index = 16, channel =  28, tsid =     0, },
  { name = "C30Ch",                           space = 3, index = 17, channel =  29, tsid =     0, },
  { name = "C31Ch",                           space = 3, index = 18, channel =  30, tsid =     0, },
  { name = "C32Ch",                           space = 3, index = 19, channel =  31, tsid =     0, },
  { name = "C33Ch",                           space = 3, index = 20, channel =  32, tsid =     0, },
  { name = "C34Ch",                           space = 3, index = 21, channel =  33, tsid =     0, },
  { name = "C35Ch",                           space = 3, index = 22, channel =  34, tsid =     0, },
  { name = "C36Ch",                           space = 3, index = 23, channel =  35, tsid =     0, },
  { name = "C37Ch",                           space = 3, index = 24, channel =  36, tsid =     0, },
  { name = "C38Ch",                           space = 3, index = 25, channel =  37, tsid =     0, },
  { name = "C39Ch",                           space = 3, index = 26, channel =  38, tsid =     0, },
  { name = "C40Ch",                           space = 3, index = 27, channel =  39, tsid =     0, },
  { name = "C41Ch",                           space = 3, index = 28, channel =  40, tsid =     0, },
  { name = "C42Ch",                           space = 3, index = 29, channel =  41, tsid =     0, },
  { name = "C43Ch",                           space = 3, index = 30, channel =  42, tsid =     0, },
  { name = "C44Ch",                           space = 3, index = 31, channel =  43, tsid =     0, },
  { name = "C45Ch",                           space = 3, index = 32, channel =  44, tsid =     0, },
  { name = "C46Ch",                           space = 3, index = 33, channel =  45, tsid =     0, },
  { name = "C47Ch",                           space = 3, index = 34, channel =  46, tsid =     0, },
  { name = "C48Ch",                           space = 3, index = 35, channel =  47, tsid =     0, },
  { name = "C49Ch",                           space = 3, index = 36, channel =  48, tsid =     0, },
  { name = "C50Ch",                           space = 3, index = 37, channel =  49, tsid =     0, },
  { name = "C51Ch",                           space = 3, index = 38, channel =  50, tsid =     0, },
  { name = "C52Ch",                           space = 3, index = 39, channel =  51, tsid =     0, },
  { name = "C53Ch",                           space = 3, index = 40, channel =  52, tsid =     0, },
  { name = "C54Ch",                           space = 3, index = 41, channel =  53, tsid =     0, },
  { name = "C55Ch",                           space = 3, index = 42, channel =  54, tsid =     0, },
  { name = "C56Ch",                           space = 3, index = 43, channel =  55, tsid =     0, },
  { name = "C57Ch",                           space = 3, index = 44, channel =  56, tsid =     0, },
  { name = "C58Ch",                           space = 3, index = 45, channel =  57, tsid =     0, },
  { name = "C59Ch",                           space = 3, index = 46, channel =  58, tsid =     0, },
  { name = "C60Ch",                           space = 3, index = 47, channel =  59, tsid =     0, },
  { name = "C61Ch",                           space = 3, index = 48, channel =  60, tsid =     0, },
  { name = "C62Ch",                           space = 3, index = 49, channel =  61, tsid =     0, },
  { name = "C63Ch",                           space = 3, index = 50, channel =  62, tsid =     0, },
  { name = "1Ch",                             space = 4, index =  0, channel =   0, tsid =     0, },
  { name = "2Ch",                             space = 4, index =  1, channel =   1, tsid =     0, },
  { name = "3Ch",                             space = 4, index =  2, channel =   2, tsid =     0, },
  { name = "4Ch",                             space = 4, index =  3, channel =  13, tsid =     0, },
  { name = "5Ch",                             space = 4, index =  4, channel =  14, tsid =     0, },
  { name = "6Ch",                             space = 4, index =  5, channel =  15, tsid =     0, },
  { name = "7Ch",                             space = 4, index =  6, channel =  16, tsid =     0, },
  { name = "8Ch",                             space = 4, index =  7, channel =  17, tsid =     0, },
  { name = "9Ch",                             space = 4, index =  8, channel =  18, tsid =     0, },
  { name = "10Ch",                            space = 4, index =  9, channel =  19, tsid =     0, },
  { name = "11Ch",                            space = 4, index = 10, channel =  20, tsid =     0, },
  { name = "12Ch",                            space = 4, index = 11, channel =  21, tsid =     0, },
]
